### ISSUE TITLE
ClientIP not parsed to ECS client.ip when it has port but no brackets 

### ISSUE THREAD

**Issue by chris-counteractive** [counteractive/o365beat#16]
Microsoft's API creates events with the `ClientIP` field in one of (at least) three different formats:

1. `10.10.10.10`
2. `[10.10.10.10]:10100`
3. `10.10.10.10:10100`

We handled the first two, but this third format (with a port but no brackets) is not handled by the current processors in `o365beat.yml`.  Fix should be something like adding the following to current `o365beat.yml`, but still needs testing:

```yaml
processors:
  - dissect:
      field: ClientIP
      tokenizer: '%{clientip}:%{clientport}'
      when:
        contains:
          ClientIP: ':'
        not:
          contains:
            ClientIP: '['
```
