### ISSUE TITLE
GCC High - Endpoint Used Returning no data

### ISSUE THREAD

**Issue by cyanitol** [counteractive/o365beat#25]
I don't see an option in the settings to change the endpoint API URLs.  When attempting to use this for GCC high environments it will not work and returns empty data due to the wrong endpoint being targeted for the API.

**Endpoint Mapping information can be found here:**
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/active-directory/fundamentals/whats-new-microsoft-365-government.md

https://docs.microsoft.com/en-us/office365/enterprise/office-365-u-s-government-gcc-high-endpoints

**Comment by chris-counteractive** [comment]
Great idea, this should be a straightforward enhancement.  We don't have a GCC high instance to test on and the docs don't cover whether there are any differences when using those endpoints - would you be able to let me know if it works once I get you a build that lets you customize those endpoints?  Should be soon.

The relevant code is [here](https://github.com/counteractive/o365beat/blob/master/beater/o365beat.go#L63-L64), I'll look to add config variables that default to the "normal" (read, commercial) endpoints, but can be updated for other environments like so:

```yaml
o365beat:
  login_url: login.microsoftonline.us  # default is https://login.microsoftonline.com/
  resource_url: manage.office365.us    # default is https://manage.office.com/
  # rest of your config ...
```
