### ISSUE TITLE
Index pattern doesn't change

### ISSUE THREAD

**Issue by ebvjr** [counteractive/o365beat#30]
Configuration:
```
setup.ilm.enabled: false
setup.template.enabled: true
setup.template.name: "testbeat-%{[agent.version]}"
setup.template.pattern: "testbeat-%{[agent.version]}-*"

output.elasticsearch:
  index: "testbeat-%{[agent.version]}-%{+yyyy.MM.dd}"
```
Expected result:
The name of new index pattern is `testbeat-%{[agent.version]}-%{+yyyy.MM.dd}`

Result:
It's still using the `o365beat-%{[agent.version]}-%{+yyyy.MM.dd}` index pattern

**Comment by chris-counteractive** [comment]
Thanks for the issue Eduardo, I'll reproduce it and see if I can track down the problem and get you a resolution.  I think all that's handled by libbeat, but perhaps I made a change that affected it without realizing.

Did you run the `setup` command against your elastic instance before shipping the logs?  Thanks again.

**Comment by opendevl** [comment]
@ebvjr could try the below configuration:

```
setup:
  template:
    name: "testbeat"
    pattern: "testbeat*"
  ilm:
    enabled: true
    rollover_alias: "testbeat"
    pattern: "{now/d}-000001"

output.elasticsearch:
  hosts: ["http://localhost:9200"]
  username: "elastic"
  password: "changeme"
  index: "testbeat-%{[agent.version]}"
```

This should give a result like `testbeat-1.4.3-2020.01.14-000001`

Thanks
