### ISSUE TITLE
Exiting: error loading config file: yaml: line 2: did not find expected node content

### ISSUE THREAD

**Issue by leogoldim** [counteractive/o365beat#36]
Hi,

I'm getting the error:

Exiting: error loading config file: yaml: line 2: did not find expected node content

When I try to start the o365beat.

`# o365beat --path.config /etc/o365beat -c o365beat.yml -e -d "*" --strict.perms=false`

```
o365beat:
  tenant_domain: company.onmicrosoft.com
  client_secret: {secret}
  client_id:     {id}  # aka application id (GUID)
  directory_id:  {id}  # aka tenant id (GUID)
  registry_file_path: /etc/o365beat/o365beat.state
  content_types:
    - Audit.AzureActiveDirectory
    - Audit.Exchange
    - Audit.SharePoint
    - Audit.General
processors:
  - add_fields:
    fields:
      tenant: {company}
  - dissect:
      field: ClientIP
      tokenizer: '[%{clientip}]:%{clientport}'
      when:
        contains:
          ClientIP: '['
  - dissect:
      field: ClientIP
      tokenizer: '%{clientip}:%{clientport}'
      when:
        contains:
          ClientIP: ':'
        not:
          contains:
            ClientIP: '['
  - convert:
      fields:
        - {from: Id, to: 'event.id', type: string}                # ecs core
        - {from: RecordType, to: 'event.code', type: string}      # ecs extended
        - {from: Operation, to: 'event.action', type: string}     # ecs core
        - {from: OrganizationId, to: 'cloud.account.id', type: string} # ecs extended
        - {from: Workload, to: 'event.category', type: string}    # ecs core
        - {from: ResultStatus, to: 'event.outcome', type: string} # ecs extended
        - {from: UserId, to: 'user.id', type: string}             # ecs core
        - {from: ClientIP, to: 'client.ip', type: ip}             # ecs core
        - {from: 'dissect.clientip', to: 'client.ip', type: ip}   # ecs core
        - {from: Parameters, type: string}                        # no ecs mapping
        - {from: ExtendedProperties, type: string}                # no ecs mapping
        - {from: ModifiedProperties, type: string}                # no ecs mapping
      ignore_missing: true
      fail_on_error: false
      mode: copy # default
fields:
  tenant: {company}
setup.kibana:
cloud.id: "{clusterId}"
cloud.auth: "{clusterAuth}"
```

**Comment by chris-counteractive** [comment]
Thanks for the issue!  Looks like this is an issue with yaml indentation.  You have:

```yaml
processors:
  - add_fields:
    fields:
      tenant: {company}
```

instead you need:

```yaml
processors:
  - add_fields:
      fields:
        tenant: {company}
```

Note the extra indentation for the `fields` tree.  This is tricky with yaml, it happens all the time.  See the [`add_fields` processor docs](https://www.elastic.co/guide/en/beats/filebeat/current/add-fields.html) for another few examples.  Let me know if this fixes things for you, and we can close the issue.  Otherwise we can dig a bit deeper.  Thanks again!
