### ISSUE TITLE
Live Realoding Credentials

### ISSUE THREAD

**Issue by cloudziu** [counteractive/o365beat#51]
Hello,
First of all great job guys with the beat!

I would like to ask if there is a possibility to add Live Reload feature. Something similar to [this](https://www.elastic.co/guide/en/beats/filebeat/current/_live_reloading.html).
```yaml
filebeat.config.inputs:
  enabled: true
  path: configs/*.yml
  reload.enabled: true
  reload.period: 10s
```
 What I would like to achieve is creating external confile with credentials, and be able to change it without restarting the beat. 
If this is achievable, are you planning to add this ?
